#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - target

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: target
    gecos: target
    shell: /bin/bash
    primary_group: target
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/8iH3S6a7qA6W4+wDsE7gztSR7/ScR4XrYFnB2UcOwi2w7KYk+b+DSoD8Oc2dPc27sknCBpKFdxn9g3+/FThGTd44sg+aihXWGpOPh7lQHqdIdMTuWvSJKooDgp1TDL/jSxe4dY9mUE17GvHYDJGGt2lM2yaemQisdlMYvTzL/s2D6VBxGp/PkMPHG0rOArbMiTJxinDbX0+niIPhlqqu6wTZhnwdeiRjx12uMQMiby1E0G4Nv7XysxzDGwxyr5ADGUVm4B9XrF0vY2aWWXFC0n2ihPe+3QsXPfK6ljJZY3jK75+lIq8dmtrJrapeexdBpZVuNS2ybqjdRgc0TwBLjbucnbO+IHd9sjIELgWYCIV24H4eCZkdjJRb16lvdFcLzOBBFtGEVjxO2xZ1TGHPOD+ql1ZkDB6v88ZdEoWAF0Twy4YUzNS5pKwf0B5sS5cGg0G0MUz3/6f281hZ+l0D67SKDXkkAYFr253hxp+3hqYPnH/HuVsU0Ah2g5sWiq0= celgee@sans.org

# Supposed to download packages but doesn't
packages:
  - ncat nmap
  #  - golang-go

write_files:
  - content: ${filebase64("./assets/hosts")}
    encoding: b64
    owner: root:root
    path: /etc/hosts
    permissions: '0644'
  - content: ${filebase64("./assets/webserve.py")}
    encoding: b64
    owner: root:root
    path: /opt/webserve.py
    permissions: '0755'
  - content: ${filebase64("./assets/webserve.service")}
    encoding: b64
    owner: root:root
    path: /etc/systemd/system/webserve.service
    permissions: '0755'

# Set up asset
runcmd:
  - whoami > /tmp/who.txt
  - sudo apt -y install nmap ncat python3 python3-pip net-tools
  - sudo pip3 install flask --upgrade
  - sudo sed -i "s/#GatewayPorts no/GatewayPorts yes/" /etc/ssh/sshd_config
  - sudo systemctl restart sshd.service
  - sudo systemctl enable webserve.service
  - sudo systemctl start webserve.service
  - echo "Hacking for cash monies!" > /opt/secrets.txt
  
