#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - attack

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: attack
    gecos: attack
    shell: /bin/bash
    primary_group: attack
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa YourPublicKeyHere

# Supposed to download packages but doesn't
packages:
  - ncat nmap
  #  - golang-go

write_files:
  - content: ${filebase64("./assets/hosts")}
    encoding: b64
    owner: root:root
    path: /etc/hosts
    permissions: '0644'

# Set up asset
runcmd:
  - whoami > /tmp/who.txt
  - sudo apt -y install nmap ncat python3 net-tools proxychains socat
  - sudo sed -i "s/#GatewayPorts no/GatewayPorts yes/" /etc/ssh/sshd_config
  - sudo systemctl restart sshd.service
  - curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  - chmod 755 msfinstall && \
  - sudo ./msfinstall
  - rm msfinstall

#   - sudo su terraform
#   - sudo mkdir /home/terraform/go
#   - sudo chown terraform:hashicorp /home/terraform/go
#   - export GOPATH=/home/terraform/go
#   - go get github.com/hashicorp/learn-go-webapp-demo
