#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - attacker

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: attacker
    gecos: attacker
    shell: /bin/bash
    primary_group: attacker
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeMq6jfpd6M2c4e2HsIW65ZdgJmTUq2YUIBBT9Eg1Eb984QsjoKc4zZz/WKSKIIw2ktRQBb2B7+hRS/Yezl8bjTs131UysYPn4rG8Ef/9HjOD8yuehOBWZupJrRDBmkDz/VkfxRqfANCACN75W4NrlgsdsLDIEWYdGsRB49YPNeXBY1pvYpXdHyVouo9dpj569m1D4zkjwsU66rNj5D6ipBqNPkPZz+8HgOBasjDJarDWTLXAm0auC17TtgtVXdAneEHdn0iGFG3/2WVkTfqVwPhCLHYsPLb1VEFqru5bXh7Vun9ELY/MiLMCtk3YdUjF2jYppL22p/uovK1ISGwsgysXK2KNB/58S8Ze/GQkbwbFvgN4vgo/EnpdhUWU4pxJXxpn3cjc7OaN99BXBk87kLbhCII22XyY2JC5xG2i3/S1CRRe6U7Js/ZarhqPsDl6Gji+dwS4duuFe+KsFX8xlbp8fS0MAZyocw703o+HSPPnL/1GVfinQt+f/9o0liNM= totally@toteslegit.us

# Supposed to download packages but doesn't
packages:
  - ncat nmap
  #  - golang-go

write_files:
  - content: ${filebase64("./assets/hosts")}
    encoding: b64
    owner: root:root
    path: /etc/hosts
    permissions: '0644'
  - content: ${filebase64("./assets/webserve.py")}
    encoding: b64
    owner: root:root
    path: /opt/webserve.py
    permissions: '0755'
  - content: ${filebase64("./assets/webserve.service")}
    encoding: b64
    owner: root:root
    path: /etc/systemd/system/webserve.service
    permissions: '0755'

# Set up asset
runcmd:
  - whoami > /tmp/who.txt
  - sudo apt -y install nmap ncat python3 python3-pip net-tools
  - echo "Hacking for cash monies!" > /opt/secrets.txt
